### ISSUE TITLE
Discussion: "line" search mode

### ISSUE THREAD

**Issue by ldelossa** [ggandor/lightspeed.nvim#100]
Hey there,

Been playing with lightspeed.nvim all morning, I really like it! 

However, I do miss the ability to quickly jump to lines like in hop.nvim

I understand that maybe not the goal of this plugin, and that's definitely understandable, but curious if there are any plans to add a "line" jump mode.

**Comment by ggandor** [comment]
Short answer: yes, I agree that that is the one mode of easymotion/hop that is actually useful for lightspeed users too, and yes, I've been thinking about this. However, I would only implement it if we could find an approach that does not feel like a patch or afterthought. And I also think that efficient selection of _line ranges_ should be the ultimate goal here.

**Comment by ldelossa** [comment]
Interesting, care to expand a but on the "without a dedicated command" bit?

**Comment by ggandor** [comment]
For example, using `s<enter>`, which is very logical, since "\r" represents a newline after the first input too. It would be more consistent actually. (The problem is that `<enter>` is currently the only way to repeat the _exact_ motion type with the previous input, e.g. `t` instead of `f`.) I think I have found a proper solution to selecting ranges too. There's a fair chance I will implement it in the coming weeks, if the repeat issue can be solved somehow, but don't take this as a promise :)

**Comment by ggandor** [comment]
Note that "jumping to a line" is only relevant for `V` selections or operations though, and the aim here is _not_ providing a substitute for `gg` jumps in Normal mode (which should not be used in the first place, since https://github.com/ggandor/lightspeed.nvim#composite-motions-do-not-compose).

Related: https://github.com/ggandor/lightspeed.nvim/tree/5763d5f651e46cdd960e4a842b30cfa50a10c2e8#startend-of-line-as-a-special-target

The only, very rare exception might be when I'd like to start entering text on an empty line somewhere.

**Comment by ggandor** [comment]
https://github.com/ggandor/lightspeed.nvim/commit/0c7f20a5f430bbd4c019f220c8bf7f6fe3b50037 partially(?) addresses this.

I'm having second thoughts about the line range selection feature though. How often would someone want to operate on a range that is not a native (or plugin-provided) text object, not an AST node that can be handled by Tree-sitter, and neither covered by some native motion (`%`, `{`, etc)?
Moreover, I cannot imagine any real-life situation where you would want (or be able) to _repeat_ an operation on such a special selection; thus, `<jump>v<jump><operation>` or `v<jump>o<jump><operation>` suffices for these cases; they're simply not frequent enough to make a dedicated interface worthwhile.

**Comment by ldelossa** [comment]
@ggandor i cant say that in native vim ive ever had the desire to "select this arbitrary line range" without my cursor being at the starting line. It gets even more constrained since that "arbitrary" line range has to be in the current view window view, which may often not be the case (and i think may break the ux of the feature anyway)

And I would agree, most multiline selection features come from motions, specially with treesitter text objects now. 

I echo your sentiments of the last message, it probably makes the most sense to have a simple "jump to a line in the current window view" but within the intuitive lightspeed interface.

**Comment by ggandor** [comment]
An enhancement that might make `s<enter>` a drop-in replacement of the dedicated linewise motions of other plugins:

When matching `newline`s in `V` mode (linewise Visual) or `{op}Vz...` (forced linewise operation)
1. we allow matching at horizontally off-screen positions too, which are skipped by default
2. the labels are displayed in the cursor column too, in addition to their original EOL positions

**Comment by ggandor** [comment]
I think with https://github.com/ggandor/lightspeed.nvim/commit/5255d8c42c6f328504d8164ceb8dee12e9fc8aac our needs are pretty much covered now. I don't think displaying labels in the cursor column too would be too helpful, it could even create a confusing/messy feel. There's no harm in leaving this discussion open for a while though.
