### ISSUE TITLE
Question regarding match highlighting

### ISSUE THREAD

**Issue by sQVe** [ggandor/lightspeed.nvim#16]
Hey 👋🏼,

I'm a bit confused if the highlighting is working correctly or not. In the 👇🏼 attached `mp4` I want to move to the last instance of `match`. 

I input <kbd>sm</kbd> and this gives me `5` hits, for `parameters` and `match`. I then input <kbd>a</kbd> and it narrows it down even further to only `match`. This is the state that is confusing to me as `lightspeed` is still highlighting `a` over the matches. I would assume it to only view valid input options and <kbd>a</kbd> is not valid in this case. The correct input would be <kbd>d</kbd>.

https://user-images.githubusercontent.com/2284724/123598507-e4781880-d7f4-11eb-8fcf-3abcebdc23ef.mp4

**Comment by ggandor** [comment]
Hi! Yeah, I've already answered this [here](https://github.com/ggandor/lightspeed.nvim/issues/5#issuecomment-862143619). The light brown(ish) `a`s are the masked characters underneath the label. They needed in the 1st stage`*`, but they won't disappear in the 2nd stage either, because that is too disorienting in my experience. It seems this can be a bit confusing at first, but still the best UI solution IMO. I will add a short primer on the highlighting strategy to the readme, I agree that it may not be self-evident.

`*` Of course, 99% of the time you obviously know/remember what you will have to type next - still, we cannot just mask the chars and leave the scene of the crime.

**Comment by sQVe** [comment]
Thanks for the answer. Closing!

**Comment by ggandor** [comment]
I'll keep this open until I have updated the documentation.
