### ISSUE TITLE
Quick-Scope like functionality.

### ISSUE THREAD

**Issue by jameswalmsley** [ggandor/lightspeed.nvim#23]
Over at LunarVim we are wanting to integrate lightspeed, some users also want to have quick-scope installed, but this is vim-script only.

Would this functionality be something you'd consider adding to lightspeed (or accepting a patch for)..

It would be great to have the one lightspeed plugin to rule them all.

**Comment by ggandor** [comment]
First, I'm really glad that you like the plugin and are considering adding it to LunarVim!

Regarding quick-scope, however, I don't think I'll ever want to add such a feature, even as opt-in. quick-scope looks very impressive at first, but I have uninstalled it after a day or so. IMHO, it is based on a flawed idea: it creates disorienting visual noise _all the time_, just for helping out in the few occasions when one wants to do an `f/t`-jump inside a line. Even the static highlighting is disorienting a bit, but those flashing letters at every single cursor movement amount to an untenable trade-off. And I'm not even sure it helps so much - if you want to target a word, it is much easier on the brain to just enter the 1-2 random characters your eyes catch first, than to process those highlighted "beacons". Sometimes the former might be slower by a fraction of a second, if you have to press repeat (1-char search) or type a label (2-char search), but that doesn't matter, because it is less cognitive load, and that is ultimately much more important.

**Comment by jameswalmsley** [comment]
@ggandor Many thanks for your detailed explanation and thought process when looking into this concept..

I'll forward a link to this on our thread about this.

I agree with what you are saying, and it is probably best to get new users to start thinking about their motion in the way you describe.
