### ISSUE TITLE
s; Semicolon  not found.

### ISSUE THREAD

**Issue by jameswalmsley** [ggandor/lightspeed.nvim#24]
If I search for a ';' then its not found, is this a known issue?

**Comment by ggandor** [comment]
I cannot reproduce this, but I suspect you tried to target a `;` at the end of a line (since that is where semicolons usually are, at least if you're not using Lisp). Was this the problem? If not, no worries, we'll look into this tomorrow.
(Related: https://github.com/ggandor/lightspeed.nvim#startend-of-line-as-a-special-target.)

**Comment by jameswalmsley** [comment]
Ah yes that's right. I was just playing around, and didn't understand this.

Thanks for the pointer.. I think I'll explore some more and read your guide a bit more closely.. you seem to have put a lot of thought into this.. many thanks 😊
