### ISSUE TITLE
sneak#is_sneaking() equivalent

### ISSUE THREAD

**Issue by mcchrish** [ggandor/lightspeed.nvim#26]
I have a mapping which looks like this:
```vim
nmap <expr> ; sneak#is_sneaking() ? '<Plug>Sneak_;' : ':'
vmap <expr> ; sneak#is_sneaking() ? '<Plug>Sneak_;' : ':'
```
Basically means map `;` to `:` when not in "label mode" otherwise let the plugin handle the mapping.

Is it currently possible to have the same behavior?

**Comment by ggandor** [comment]
It should be possible. The equivalent of `sneak#is_sneaking()` is `require'lightspeed'.ft['instant-repeat?']` here. (This is obviously for 1-char search only.) So the workaround described in `:h lightspeed-custom-ft-repeat-mappings` should be modified accordingly, to use `expr` mappings. (I'm having a hard time hacking that together though, but will report back if I succeed.)

**Comment by ggandor** [comment]
Oh, sorry, I got it wrong, it's not possible with `instant-repeat?`, we cannot simply initialize that to `true` instead of `nil` (and thus use it as a pseudo `is_sneaking` i.e. `lightspeeding?` flag), that would break many things. We would have to expose a dedicated flag, or alternatively, `LightspeedEnter`/`LightspeedLeave` events. I'll think about it.

**Comment by romgrk** [comment]
A flag would be really nice, just add something like `ft['is-active']`, it's more than enough. I'm having the same issue, one of my mappings requires `sneak#is_sneaking` and it can't be done currently.

**Comment by ggandor** [comment]
@romgrk Okay, will do this, but, FYI, it's not that simple :) The `ft:to` function gets the next keypress and feeds it forward in any case. If we simply set the flag to false when the function exits, the fed keypress will already see it as inactive (I tried it). So we need to set up an autocommand on a bunch of events to deactivate the flag after exit, and in particular, a nested autocommand, because the first CursorMoved event should be skipped (that should not short-circuit the ft-movement yet, because we might want to repeat again). This is what Sneak does, if I'm not mistaken, I need to check the source to refresh my memory...

**Comment by ggandor** [comment]
@romgrk I haven't been able to do this with CursorMoved yet (we have a very different design than Sneak it's not 1-1 portable), I really cannot follow what's happening between the main function, `feedkey`, and the autocommands anymore :D.

On the other hand, there is a beautiful, clean solution readily available for repeating (we can simply offer `opts` fields, like `ft_instant_repeat_fwd_key`, so the whole thing happens inside the function, like group-switching for `s`). I'm curious, what custom mapping do you have in mind that is not about the repeat functionality?

**Comment by romgrk** [comment]
Don't really like this solution, I use `sneak#is_sneaking` inside a function that handle my normal-mode `;` mapping. That keys does many things (because it's right under my finger), and it's dependant on the context. Tuning it for the right behavior is done in a function with many parts, one of them being `if sneak#is_sneaking() then call sneak#rpt()`.

**Comment by ggandor** [comment]
@romgrk  I see, makes sense. Fortunately we also have User events now, so you can use `LightspeedEnter`/`LightspeedLeave` as a more flexible option then (to set a global flag, for example).

**Comment by romgrk** [comment]
An `require'lightspeed'.is_active` flag would be awesome. I've tried to do the change myself but my lisp isn't good enough to defeat the `exit-template` macro -_-

**Comment by ggandor** [comment]
Okay, it will be done.

Out of sheer curiosity (maybe I can steal some ideas): in what different roles do you use `;`?

**Comment by ggandor** [comment]
> tried to do the change myself but my lisp isn't good enough to defeat the exit-template macro -_-

Yeah, I'm a bit worried about the bus factor sometimes, but Lisp is an insane productivity boost, and after all, this is just an editor plugin, not NASA software. :) I always try to find the time to refactor and document the codebase as much as possible.

**Comment by romgrk** [comment]
If sneak is active, `;` repeats it. If it's not, it activates some "quick commands", e.g I only need to press `;w` to save the file, not `:w<CR>`. If there is no quick command, it starts command mode. Context-dependant mappings are quite useful, some other examples:
 - `<a-h>` does the same as `^`, unless it's already at the first non-whitespace char, then it acts as `0`
 - `v` cycles through visual modes depending on which mode is active
 - `<esc>` closes active coc floats if there are some, otherwise runs `:nohl`

**Comment by ggandor** [comment]
Okay, so I've been pondering on this.

Flagging in itself is trivial, I don't think I want to expose a flag at all, I really want to keep the interface as small as possible. The very point of `LightspeedEnter`/`LightspeedLeave` is that we can decouple all such stuff from the script itself. It's a scalable DIY toolkit, and they make fine-grained tweakings possible for free; instead of having to expose 3 different flags for e.g. `ft`/`sx`/`any`, one can just set up autocommands as they like. On a side note, this is also in line with Lua's "mechanisms, not policies" approach.

```Vim
" just two lines:
autocmd User LightspeedFtEnter lua require'lightspeed'.is_ft_active = true
autocmd User LightspeedFtLeave lua require'lightspeed'.is_ft_active = false
```
You can use <expr>-mappings then, like:
```Vim
nnoremap <expr> ; v:lua.require('lightspeed').is_ft_active ?  '...' : '...'
```
Of course, instead using the `lightspeed` module, a `g:` variable with `unlet` and `exists('...')` checking in the mapping is also fine.

But the real problem lies elsewhere. Sneak simply exits the function, and before that, sets an autocommand that switches off `is_sneaking` on certain events.  That is a messy solution for sure[1], but ours has its own set of trade-offs too.  We always just `getchar` the next input unconditionally, and if we're not interested in it, then feed it forward _and_ exit. In any case, the logic that handles repeating has to be hardwired into the function. Currently we're checking whether the input is `<Plug>Lightspeed_t`/`<Plug>Lightspeed_f` or `opts.instant_repeat_fwd_key` (plus the reverse versions obviously).

And we should know whether we're repeating `f` or `t`, so if we'd like to solve this in a decoupled way, from the "outside", we should rely on the non-official, non-frozen API, i.e. the `ft` table itself. So in the end, it's not a final solution (yet), but it's still cleaner to just use the existing infrastructure:

```Vim
nnoremap <expr> ; v:lua.require('lightspeed').is_active
            \ ? v:lua.require('lightspeed').ft.state.cold['t-mode?']
            \ ? '<Plug>Lightspeed_t' : '<Plug>Lightspeed_f'
            \ : ':'

nnoremap <expr> , v:lua.require('lightspeed').is_active
            \ ? v:lua.require('lightspeed').ft.state.cold['t-mode?']
            \ ? '<Plug>Lightspeed_T' : '<Plug>Lightspeed_F'
            \ : ':'
```
I will certainly rethink those tables in the future, but once they are ready, this will be the way to go. I'll just put the above snippet (updated) into the wiki/readme/help, and might even deprecate the `opts` keys for instant-repeat.

[1] For example, an intricate hack is needed just to make `<esc>` exit Sneak, that doesn't even work if `<esc>` is already mapped in Normal mode.

**Comment by ggandor** [comment]
Thinking a bit more about this, the 100% do-it-yourself-with-autocommands approach might be a bit too spartan. But instead of a flag, it would be better to expose an `active_motion` variable, that returns the exact type (f/F/t/T/s/S/x/X), or `nil`.

**Comment by romgrk** [comment]
I really dislike the extract-your-own-state-information. It feels unclean, and it also means that each person that want to do this will need to understand everything you posted above. If it's exposed as a clean API, the code is only repeated in the plugin, not in everyone's config, and there is much less cognitive load.

If all plugins did this kind of thing, I'd end up with an horrible config. I'd need to maintain code that is dependant on this plugin's API & architecture.

The `active_motion` thing would be fine.
