### ISSUE TITLE
fFtT repeats do not work with vim-cutlass

### ISSUE THREAD

**Issue by bwells** [ggandor/lightspeed.nvim#28]
When [svermeulen/vim-cutlass](gitHub.com/svermeulen/vim-cutlass) is registered after lightspeed the repeating single character searches does not work. The initial single character search still works, but pressing, as an example, `f` again just starts a new `f` single character search. 

I'm able to work around this issue by 

    nnoremap s <nop>
    Plug 'svermeulen/vim-cutlass'
    unmap s
    Plug 'ggandor/lightspeed.nvim'

but thought you might want to be aware of the potential conflict. In particular cutlass does not, that I can tell, ever mess with any of fFtT.

**Comment by ggandor** [comment]
Thanks for reporting! Interesting issue, I will read through the `cutlass` script and get to the bottom of this, when I find the time.

**Comment by physicophilic** [comment]
I am also getting this.

**Comment by TheBlob42** [comment]
I just switched to lightspeed (great plugin btw) over from `sneak` and this annoyed the heck out of me too :see_no_evil: 
After digging through the `cutlass` script and your code I am confident I found the reason for this behavior.

`cutlass` is registering a mapping in select mode for every single character, so that when you start typing the selected text which gets deleted is not written into the default delete register (see [here](https://github.com/svermeulen/vim-cutlass/blob/master/autoload/cutlass.vim#L2-L22))

When looking into the `ft.to` function of `lightspeed` I found that there is a check if a `<Plug>Lightspeed_[fFtT]` mapping is mapped in the current mode (see line [507](https://github.com/ggandor/lightspeed.nvim/blob/main/fnl/lightspeed.fnl#L507))

```fnl
(set self.instant-repeat? 
   (and ok? (string.match (vim.fn.maparg in2) "<Plug>Lightspeed_[fFtT]")))
```

If you call `vim.fn.maparg` without the second `mode` parameter it will check the default mapping as if using `:map <characters>` from within NVIM. Now the issue appears as `:map` will check normal, visual, operator and select mode for bindings to the given characters. If you have `lightspeed` and `cutlass` installed and enter `:map f` your output should show the following:

```text
s  f           * <C-O>"_cf
o  f             <Plug>Lightspeed_f
x  f             <Plug>Lightspeed_f
n  f             <Plug>Lightspeed_f
```

The first binding is the `cutlass` binding from the function I mentioned at the start of this comment.

Now when you execute `:lua print(vim.fn.maparg('f'))` you will not get an array of all bindings available but just of the first one:

```text
<C-O>"_cf
```

Therefore the check for the instant repeat will always fail and we get the behavior we have monitored.  
To solve this the current mode needs to be passed to the `maparg` function.

**But beware** that `maparg` use different characters to describe some modes than you would get from `vim.fn.mode()` (which returns the current mode). So simply passing `vim.fn.mode()` as second parameter here will only fix the issue for normal mode but not for visual. `vim.fn.mode()` in visual mode will return "v" or "V", but `maparg` uses "v" for visual AND select mode, so we have to use "x" instead (check the documentation of both functions). I don't think any other mode besides normal and visual is interesting here :thinking: 

Based on this I came up with a simple solution in lua as I have no experience writing fennel. 
(see the compiled (?) lua code at line [645](https://github.com/ggandor/lightspeed.nvim/blob/main/lua/lightspeed.lua#L645))
```lua
local current_mode = vim.fn.mode()
if current_mode:find('[vV]+') then
     current_mode = "x"
end
self["instant-repeat?"] = (ok_3f and string.match(vim.fn.maparg(in2, current_mode), "<Plug>Lightspeed_[fFtT]"))
```

@ggandor maybe you can "translate" my lua version into the appropriate fennel code for the plugin :slightly_smiling_face:

**Comment by ggandor** [comment]
@TheBlob42 Awesome. Thank you for the fix _and_ the detailed explanation.

Moreover, checking the mode also handles the unlikely (but technically possible) case if someone maps different keys for ft-search in Normal and Visual mode.

For the current mode, we should check blockwise (`<ctrl-v>`) too, so `[vV]+` wouldn't suffice I guess, we need to call `replace_termcodes`, etc., starts to become too complex to do that on the spot. On the other hand, we could get away with a much simpler solution, since I have only exposed <Plug> keys for `x` mode (not `v`). Since we are not in operator-pending mode (that has been checked above), if it the mode is not Normal, then it should be Visual. (Well, one could technically make Select-mode mappings that call the Lua functions directly, but it's their responsibility from then on, the `ft` table is not part of the official API.)

You're more than welcome to do a PR yourself if you want some contribution credit :) Here is the Fennel snippet:
```Fennel
(set self.instant-repeat? 
     (and ok? 
          (let [mode (if (= (vim.fn.mode) :n) :n :x)]  ; vim-cutlass compat (#28)
            (string.match (vim.fn.maparg in2 mode) "<Plug>Lightspeed_[fFtT]"))))
```
If you [download](https://fennel-lang.org/setup#downloading-a-fennel-binary) the most recent Fennel executable, and put it on the path, you can just `make` it before commiting. (But of course I can just push this right now if you don't want to bother with it.)

**Comment by TheBlob42** [comment]
@ggandor thanks for providing me with the Fennel snippet :slightly_smiling_face: 

Can you check if the opened PR is correct and if so merge it?

**Comment by ggandor** [comment]
@TheBlob42 Everything's fine, thanks very much again for the fix!
