### ISSUE TITLE
Missing target

### ISSUE THREAD

**Issue by andrew-scala-zapier** [ggandor/lightspeed.nvim#29]
Running command `Se` and I noticed that I don't get a prompt for one of the e's above

![16a43856ef7e10d8fd29265e9a976619](https://user-images.githubusercontent.com/84349424/127024822-8758cbe0-9b38-45ad-a304-47a3334f7d42.png)

**Comment by ggandor** [comment]
Hi! It is not highlighted, because it is the last character on the line, so there's no potential target for 2-character search there. Theoretically we could support targeting characters before EOL (e.g. `enter` could represent `\n`), but I've addressed this issue [here](https://github.com/ggandor/lightspeed.nvim#startend-of-line-as-a-special-target), and I don't think it would make much practical sense, after all.
