### ISSUE TITLE
Provide a way to map ; and , (or custom keys) to repeat f/t motions

### ISSUE THREAD

**Issue by ggandor** [ggandor/lightspeed.nvim#3]

**Comment by svanharmelen** [comment]
Yeah not having the ability to prevent mapping fFtT and also not have the ;, work as expected is a is frustration/limitation with using this plugin...

**Comment by ggandor** [comment]
You can disable that if you want, just map dummy key(seq)s to the corresponding `<Plug>` keys (`:h lightspeed-disable-default-mappings`). (Or, if you've been using Sneak: mapping `f/F/t/T` to Sneak's corresponding commands also works.) As for mapping `;,`, I am working on a clean solution. I don't really want to _encourage_ that, but I see that I should provide some workaround for people who (have to) use vanilla Vim a lot, and cannot undo the muscle memory.

**Comment by svanharmelen** [comment]
I tried adding:

```
nnoremap lf <Plug>Lightspeed_f
nnoremap lF <Plug>Lightspeed_F
nnoremap lt <Plug>Lightspeed_t
nnoremap lT <Plug>Lightspeed_T
```

But it still remaps the default fFtF keys...

**Comment by svanharmelen** [comment]
>  I don't really want to encourage that, but I see that I should provide some workaround for people who (have to) use vanilla Vim a lot, and cannot undo the muscle memory.

So how would you suggest to do it? If if do `f,` it highlights all `,` but doesn't allow we to chose which to jump to. So is that a bug then?

**Comment by ggandor** [comment]
> 
> 
> I tried adding:
> 
> ```
> nnoremap lf <Plug>Lightspeed_f
> nnoremap lF <Plug>Lightspeed_F
> nnoremap lt <Plug>Lightspeed_t
> nnoremap lT <Plug>Lightspeed_T
> ```
> 
> But it still remaps the default fFtF keys...

You should use `nmap`, when mapping to `<Plug>` keys, since these should work recursively - they are aliases for other mappings. But I don't recommend `lf`, etc., because that will cause a lag every time you press the `l` key. Use something like `<C-F12>` that won't collide with anything... you get the idea.

**Comment by svanharmelen** [comment]
I tested the workaround for `;,` and it seems to work great (at least in normal mode). So in that case I don't mind that fFtT are remapped, I can use them in the same fashion now 👍🏻

**Comment by ggandor** [comment]
Oh, got it, Visual mode is also ok, I just forgot to use `<cmd>` in the Vimscript example (the Lua snippet is fine). Correcting the docs in a minute.

**Comment by ggandor** [comment]
> 
> 
> It still remaps f...
> 
I guess the problem is that you remapped them _after_ the plugin has loaded... Would you please try that again, putting those lines before the `Plug` section, so that we can close this? Thanks very much!

**Comment by svanharmelen** [comment]
Just tested it and if mapped before plugging, it indeed works 👍🏻

**Comment by andrevmatos** [comment]
The suggested `fun!` doesn't seem to work on visual selection for `t`/`T`: if I'm visually selecting with `t`, and type `;`, it seems to recall previous `f` operation, instead of the current `t` one

**Comment by ggandor** [comment]
@andrevmatos You probably used a simple `:call`, instead of `<cmd>call`, isn't that the problem? It should work with the latter.

**Comment by andrevmatos** [comment]
@ggandor thank you for your response, I had just copied the command from a previous commit, and it was not working because I had some `t?` binds on my config which seems to prevent `t` moving from working properly in `x/v` mode.

Unfortunately, it's still not working perfectly: by moving with `f`, I can move correctly between two consecutive occurrences of a character with `;` and back with `,`, but if I try to do the same with `t`, it seems that the first time I switch between `;` and `,`, it skips one occurrence. e.g. if I'm in the beginning of a line with 4 letters `x`, and type `tx`, it'll go to the 1st `x`, pressing `;` will go to the 2nd, and again, to the 3rd and 4th, but then if I press `,`, it'll jump to the 2st, and again to 1st, and back to `;` wil jump to 3rd and 4th.
This is seem both on normal and visual selection modes. It doesn't occur with `f`.
Thank you again for your support and the great plugin.

**Comment by ggandor** [comment]
@andrevmatos Good catch! This is not because of the workaround, repeating with `t/T` behaves the same way. I know where the problem is, raised a separate issue (#19). Thanks again for catching this.
