### ISSUE TITLE
Space character in labels

### ISSUE THREAD

**Issue by flosker** [ggandor/lightspeed.nvim#39]
**And** useless search character prefix, which confuses user.

#### Screenshot 1
![Screenshot](https://user-images.githubusercontent.com/86894799/130344322-4de71f92-3f07-4594-80e0-750b8dd6b325.png)

#### Screenshot 2
![Screenshot 2](https://user-images.githubusercontent.com/86894799/130344825-4a4bdee7-ed44-4a31-b555-168bd92024e6.png)

#### Screenshot 3 - Hop
![Hop short jumps](https://user-images.githubusercontent.com/86894799/130345135-f53d0b96-54ad-4131-aafb-f218af8c824d.png)

#### Screenshot 4
![Screenshot 4](https://user-images.githubusercontent.com/86894799/130345880-c98effba-61c3-48b1-9f71-d6905d9fb9c3.png)

1. In screenshot above, I searched for `e`, The green color parts don't need first `e` to jump to, so they are confusing.

2. `f` & `j` in purple color need `space` key to be pressed first, which is not obvious, and space is neither in the labels config.

3. **And** why do I have very few 1 character jumps in Screenshot 2? Hop & Easymotion make jump labels as short as possible. See Line 1-6 in Hop screenshot.

4. In Screenshot 4, there is a capital `H`, which I didn't include in labels config, why is it there?

How to remove `space` form labels & e from those green color areas.

### Config
```
require'lightspeed'.setup({
	jump_to_first_match = false,
	highlight_unique_chars = false,
	grey_out_search_area = true,
    -- Target keys
	labels = {'d', 'k', 'f', 'j', 's', 'l', 'a', ';', ',', 'c', 'm', 'e', 'i', 'w', 'o', 'g', 'h', 'v', 'n', 'r', 'u', 't', 'x', ',', 'q', 'p', '[', ']', 'z', '.', '/', 'y', 'b'}
})
```

**Comment by flosker** [comment]
EDIT: I just found out Hop also has character jump feature, so I am staying with it. Keeping this open, so you can improve this plugin.

**Comment by ggandor** [comment]
Hi there! 

I suspect you are misunderstanding how the `s/S` command should work (but that's fine, it means the documentation should be improved). Lightspeed's `s/S` is _not_ like `HopChar1`, it's like an enhanced version of `HopChar2`. You should enter two characters as a search pattern, and you'll see _one_ target label, that is an invariant. It is just a visual aid that the labels are visible right after the first input, so your brain can process them _before_ you actually need to type them (this is one of the main inventions of this plugin). But you should type the second character in the pattern anyway. The advantage over Hop(/EasyMotion/Sneak)'s implementation is that while you're typing that second character, you already see the label, so there's no pause needed after that.

A quick primer on how the highlighting works. After entering the first character of the pattern, let's call it `A`, you see _all_ possible 2-char matches that start with `A`. If `jump_to_first_match` is on, then certain matches will be highlighted as they are (the green ones here), without labels (hints in Hop terminology). Like `eH` in your example. That means you just have to type `H` after `e` (well, finishing the pattern), and that's all.

All other matches look like this (let's say you'd like to jump to `AB`):
original on-screen characters:
[`A`][`B`]
after entering `A`, i.e. the first input:
[`A-that-is-now-masked-by-the-label`][`label (_always_ one character)`]

So those spaces are not labels, those are possible `AB` = `e<space>` matches, with `B` - that is, a `space` - shown in the first column, and the label in the second.

But there are a bunch of things on these screenshots that confuse me. My very first question: what colorscheme are you using? Why does the highlighting look like exactly the same as Hop's? Are they overriding Lightspeed's highlight groups? Because this highlight scheme makes it extremely confusing indeed. In the [relevant section of the readme](https://github.com/ggandor/lightspeed.nvim/tree/177ef542f6f26147f16be7b07c1e6fcfa66bf128#ahead-of-time-labeling), you can see yourself that with the default highlighting the "masked" second characters (shown over the first ones) are _much-much_ dimmer and less obtrusive than the labels (that are also underlined btw).

Moreover, if `jump_to_first_match` is turned off in the config, then there shouldn't be any "green" matches in the first place... (i.e. unlabeled ones, that are directly reachable.)

It would be great if you'd give it another try, now that the usage is - hopefully - clearer. I'm ready to answer any remaining questions/issues you have.

**Comment by flosker** [comment]
1. Why does the highlighting look like exactly the same as Hop's?
Because I configured the highlight groups. I found default highlighting to be confusing.

2. `jump_to_first_match` is indeed turned **off**.

I will give it a shot!

**Comment by flosker** [comment]
I tried & now it makes sense! I will probably keep using this one I guess, as it takes same amount of keys, but is more intuitive.

I do have one question, is it possible to ignore case? like in above `eH`?

**Comment by ggandor** [comment]
> I tried & now it makes sense! I will probably keep using this one I guess, as it takes same amount of keys, but is more intuitive.

Okay, cool, I'm glad! I hope the highlighting makes sense now, everything has a reason there. If you decide to tweak the colors though, you should definitely keep assigning distinct attributes to the different groups, like [shortcuts](https://github.com/ggandor/lightspeed.nvim/tree/177ef542f6f26147f16be7b07c1e6fcfa66bf128#shortcuts), or overlapped matches.

> I do have one question, is it possible to ignore case? like in above eH?

Not at the moment, unfortunately. For this plugin, it's technically challenging, both implementation and UI-wise (it would become problematic to decide how to assign the labels ahead of time). I have already [addressed this issue](https://github.com/ggandor/lightspeed.nvim/tree/177ef542f6f26147f16be7b07c1e6fcfa66bf128#ignore-case-for-2-character-search) in the Readme. I'm thinking about it, but it's a non-trivial task.

**Comment by flosker** [comment]
Alright that's no big deal! Thanks for this great plugin ;)
