### ISSUE TITLE
Disable conceallevel while lightspeed is active

### ISSUE THREAD

**Issue by IndianBoy42** [ggandor/lightspeed.nvim#42]
the problem is that when conceallevel > 0 you can't really see where you are trying to jump to. So it would make to disable conceal while jumping.

Is there anyway easy way to do this? or could this be feature of this plugin?

**Comment by ggandor** [comment]
Yeah, I see. There's no easy way I'm afraid, it has to to be handled by the plugin, similarly to `scrolloff`. These are always a bit messy because of the many-many exit points from the main function. The other alternative is to introduce `LightspeedEnter`/`LightspeedLeave` events, that can handle all such temporary option-switchings, and are readily available for many other things too.
