### ISSUE TITLE
Include Boolean Option for native , and ; character search

### ISSUE THREAD

**Issue by jam1015** [ggandor/lightspeed.nvim#47]
This suggestion naturally follows from the second part of https://github.com/ggandor/lightspeed.nvim/issues/46 

Include boolean option for including native `;` and `,` functionality, rather than suggesting that the user copy one of the implementations that are included in the documentation; this will help avoid further clutter in users' config files, and also simplify the documentation.

**Comment by ggandor** [comment]
First, are you aware that you can set custom keys for "instant-repeating" now? (See the relevant section [here](https://github.com/ggandor/lightspeed.nvim#1-character-search).) If not, then I think that is what you're looking for, and the issue is solved.

If you're indeed talking about the actual native behaviour, then raise everything to ² that I wrote [here](https://github.com/ggandor/lightspeed.nvim/issues/25#issuecomment-877226474), and especially in [this answer](https://github.com/ggandor/lightspeed.nvim/issues/25#issuecomment-877226474), regarding `s` + `;`.

The hack described in `:h lightspeed-custom-ft-repeat-mappings` is what it is - a hack. I don't want to hardcode a solution for supporting the native Vim behaviour _in addition_ to the above mentioned "temporary hijacking" option, because nobody have come up with a use case so far where that would make actual sense.
