### ISSUE TITLE
If the third character make the match unique, use that third character to jump and why the reminder character should stay on screen

### ISSUE THREAD

**Issue by GGCristo** [ggandor/lightspeed.nvim#5]
If the third character make the match unique, use that third character to jump, this way we can reduce the "surprise" factor.

In this case if I search for `pr` there are only 2 possibilities: `project` and `previousTctTask_`
![fullScreen](https://user-images.githubusercontent.com/58046649/122114167-e87e6080-ce1a-11eb-8700-75b27ab1d664.png)
The ideal it would be I could jump to `project` with `o` and `previousTctTask_` with `e`

The jump to the first match could be automatically, but you get the idea.

Also, it is necessary that `r` when I have already pressed `pr`?
![Captura de pantalla de 2021-06-15 20-52-37](https://user-images.githubusercontent.com/58046649/122114869-b6b9c980-ce1b-11eb-96bc-ef1883c73a19.png)

**Comment by ggandor** [comment]
This is a good idea - in fact, I have [already thought about it](https://github.com/ggandor/lightspeed.nvim#-coming-sooner-or-later). Caveat: unfortunately we cannot use this together with auto-jumping, because in that case we want to "fall through" with any non-label characters, continuing editing, that is the point of the feature. (In your example: it might be that I jumped there because I wanted to open a new line - `o`, or append to the end `ea`.)

The reason why the `r` should stay on the screen is to mitigate the disorienting visual stimuli while targeting. If that reminder character suddenly disappears in the third step, then your brain will unwillingly shift the focus to that change, instead of concentrating on the label. (I tried that while developing the plugin.) For that very same reason, when overlapped pairs (e.g. `ed` in `eed`) come to the surface in the 3rd round, their label keeps the same, paler highlight, and does not change back to "normal".

**Comment by GGCristo** [comment]
I see, this idea would make the jump faster but the general workflow would be slower if auto-jump is activated.
I don't know if the "reminder character"  is the best idea, but I guess you have played a lot with the options and that is the conclusion you came up. I was thinking in something like: "everytime I see a strong color I should hit that like a wac-a-mole"
Well, thank you for the plugin it's already fantastic and good luck in reaching a Psychokinesis level 😆
