### ISSUE TITLE
Interferes with nvim-cmp + snippet variables

### ISSUE THREAD

**Issue by sQVe** [ggandor/lightspeed.nvim#67]
👋🏼,

I use `nvim-cmp` for completion together `vsnip`, which is two pretty common plugins. I noted that I cannot change the name of some snippet variables and now understood why.

If I try to change the variable to something that starts with an `s` or `S` it doesn't work due to `lightspeed` having that binding in visual mode. Unsure how to fix this but it is very annoying. 

See below video of problem. At `t` I'm trying to write `searchKeys` but it's not letting me.

https://user-images.githubusercontent.com/2284724/139316063-15b5ed5b-0c8d-40a6-962c-db8a88cb7e9d.mp4

**Comment by ggandor** [comment]
I'm a bit lost, could you elaborate some more? :) Is the problem with nvim-cmp then, but only in the context of a vim-vsnip snippet? I also don't understand it yet why is this specific to Lightspeed, if the problem is occupying a binding in Visual mode. What about any other keys?
As for a workaround, aren't there some `Enter`/`Leave` events maybe, that could be used to switch off Lightspeed while snippet-mode is active?

**Comment by sQVe** [comment]
@ggandor That makes total sense. I'll raise the issue there instead and reference this issue.

And you're correct. I'm seeing this issue when using vsnip and moving to snippet variables and pressing s. So the issue should probably be owned by vsnip, I guess 🤷‍♂️
