### ISSUE TITLE
Feature request: f and t - show number of key presses needed to reach position

### ISSUE THREAD

**Issue by quantum-booty** [ggandor/lightspeed.nvim#68]
![image](https://user-images.githubusercontent.com/28958399/139498174-7de7d3a4-94c6-4347-b483-bb047609184e.png)
It would be nice to show the number of keypresses needed to reach each positions. Is this possible via ghost text just above the highlighted characeters?

**Comment by ggandor** [comment]
Technically simple, yes, but I don't think this makes much sense. Let's put it aside for a moment that there are edge cases that would make this hard, if not impossible, to implement UI-wise in the first place (what if we're on the topmost line, what if a match is right above another match, etc.).  Why not just label the matches then, and press one letter to reach the target? But regarding that, I've already written down the [counter-arguments](https://github.com/ggandor/lightspeed.nvim/tree/1afd406a80b42eaabba8c624bea5e7571e7e74fb#labeled-matches-for-1-character-search), it's not going to happen.

In general, `f`/`t` should be pretty rarely used in this plugin, and mostly with operations. You really shouldn't use `f`/`t` in situations when you're just blindly approaching the target, without clearly seeing the road beforehand (i.e., knowing the count). That's what `s` is for. Why would anyone want to press `f`, say, 5 times (`fxfffff`) when there is `sxy(l)`?

**Comment by bmulholland** [comment]
What about just highlighting the first available match? As in https://github.com/gukz/ftFt.nvim

**Comment by ggandor** [comment]
@bmulholland I think that's too much noise, for little gain. What's the use case, especially in Lightspeed? Maybe it could help preventing messing up an `{op}f{char}` operation when you do not notice an in-between character (very rare I guess), but otherwise it would only be a gimmick. As I said above, `f/t` should only be used when you see the road clearly, they're not for going out into the wild and then repeating as needed, following the "lights", that's totally inefficient.

**Comment by bmulholland** [comment]
Maybe I just need to break my habit of using f and t :)
