### ISSUE TITLE
question: how to debug, if tab or jumps dont work

### ISSUE THREAD

**Issue by matu3ba** [ggandor/lightspeed.nvim#71]
Sidenotes, which make `s` and `S` mode unfortunately too unreliable for me:
On text editing I get many false jumps with both. 
On pressing `S,p` I get multiple possible results.
Big chars seem to be directly jumpable and lower characters need cycling.
However, this behavior is not consistent with reddish characters also often being directly jumpable.

Grayish characters are at least consistently directly jumpable, but there are also occurences of a gray character
being after reddish ones (which is very annoying).

Tab from the  does not work for some reason. How can I debug the causes for this?

**Comment by ggandor** [comment]
> On pressing S,p I get multiple possible results.

What do you suppose I should do with this without a screenshot or a snippet with the window content? :D

> Big chars seem to be directly jumpable and lower characters need cycling.

I don't really understand what do you mean by "big" and "lower" but I guess "closer" and "more distant"? Anyway, that is totally natural after the _first_ input. That is the point, first we're labeling all `x?` matches _in parallel_, and after entering the second input (`y`), we're reducing them to the `xy` matches. (Then here shouldn't be unlabeled matches after labeled ones.)

> there are also occurences of a gray character being after reddish ones (which is very annoying)

If you mean the "brown" characters before the labels, those are just the characters masked by the labels. If not, then see the previous answer.

> Tab from the does not work for some reason

`tab` only works after entering the second character (i.e., entering `y`, if you're searching for `xy`, _if_ there are more matches for `xy` than labels available.

I suggest you first study the [usage](https://github.com/ggandor/lightspeed.nvim#2-character-search-sx) and the [in-depth intro](https://github.com/ggandor/lightspeed.nvim#-an-in-depth-introduction-of-the-key-features) thoroughly, and also [this short explanation](https://github.com/ggandor/lightspeed.nvim#a-note-on-the-highlighting-strategy) on the highlighting, and if the system is still not clear, I'm happy to help, provided you attach a screenshot, so that I can refer to that while explaining.
