### ISSUE TITLE
Omni direction

### ISSUE THREAD

**Issue by timsofteng** [ggandor/lightspeed.nvim#8]
Hello. The main reason why I use hop is Omni-direction. I can press just shortcut for `:Hop2char` and press two characters and move both top or bottom direction. I don't care about two different shortcuts.
May I do it with `lightspeed`?

**Comment by ggandor** [comment]
Hi there! I have expected this request, and specifically [addressed in the readme](https://github.com/ggandor/lightspeed.nvim#bi-directional-search), listing the counter-arguments. I encourage you to give Lightspeed a try though, and then decide: with Hop you can never be this fast, because (1) you have to wait for the hints to appear _after_ pressing the two characters (and your brain needs time to process them), and (2) on average,  you have only half as many positions that are reachable via one hint (i.e. additional keypress), exactly because of omni-directional search.

**Comment by timsofteng** [comment]
Oh. I haven't read this far:D

You forget two important things:
1. Break to decide which direction you should use. / and ?, f and F kill freeze me always especially when I code hard.
2. Hop has 1-character engine as well.

Nevertheless I really appreciate your work!

**Comment by ggandor** [comment]
You see the cursor, and see the target - I don't get it why you would have to think consciously about the direction? It's totally instinctive.

Lightspeed also has 1-character search, but for short distances especially, without hints/labeling. That would be pretty pointless, because the "break" is inevitable then, physically impossible to show them ahead of time, and also there are too many targets usually. Isn't it much better to type 2 on-screen characters, and wait for 1 "surprising" hint/label (and in Lightspeed it's actually _not that_ surprising!), than to type 1 on-screen character, and wait for - most probably - 2 "surprising" chars?

But anyway, thanks for the kind words :)

**Comment by timsofteng** [comment]
It looks like you have chosen the wrong profession. You are a born lawyer. I'll try it tomorrow!

**Comment by timsofteng** [comment]
I've tried it.
And can't understand how can I get to this `vim` word?
I press `s` then `i` then `f`?
Doesn't work.
I've tried different combinations but it doesnt get me to that location.

**Comment by ggandor** [comment]
> 
> 
> It looks like you have chosen the wrong profession. You are a born lawyer. I'll try it tomorrow!

Lol, I've never thought about that... :)

> And can't understand how can I get to this `vim` word?
> I press `s` then `i` then `f`?

Press `s`, then the two characters you're targeting (`char1`, `char2`). The "labels" ("hints" in Hop terminology) will appear right after you enter the first character, for _all_ `char1`+`X` matches. Pressing the label won't take you to your target yet (except in special cases), because all the different possible target pairs are labeled up in "parallel" in this phase; you have to type the second character too - then you can see that only the `char1`+`char2` matches remain on screen - and then type the label to jump there. The advantage is, however, that you do not have to pause after entering `char2`, you see the label beforehand, and can continue to type it, without any break in the flow, as if it would have been an on-screen character.

Now the special case I mentioned is when the label is not colliding with any of the `char2`s among the other matches. These are what Lightspeed calls "shortcuts": the label gets a different highlight then (white character in a red-ish block, the inverse of a regular label); and these you can reach right after entering `char1`.

**Comment by ggandor** [comment]
I'm closing this now, but feel free to continue the discussion.

**Comment by ggandor** [comment]
Implemented by 46d111b2f61fb7b96762f1f0dd36525b820711ad.
