### ISSUE TITLE
Default semicolon bind

### ISSUE THREAD

**Issue by milisims** [ggandor/lightspeed.nvim#85]
Installing this plugin breaks default `;` functionality without configuration, which seems counter to "cohesion, conceptual integrity, and reliability". 

In the same vein, is there a reason there are two separate `<plug>` maps for `;`? Seems "cohesive" to me to have one map for both of them, and easily done: keep track of which was used last and repeat that motion.

**Comment by ggandor** [comment]
> Installing this plugin breaks default ; functionality without configuration, which seems counter to "cohesion, conceptual integrity, and reliability".

That doesn't mean we should keep every sub-optimal feature from vanilla Vim. Same-key repeat is clearly superior, as `f`/`t` are just as convenient keys as `;`/`,`, but much more intuitive (the search trigger is also used for repeats, instead of some other, arbitrary key). Your argument would be relevant if e.g. `;`/`,` would repeat `/`/`?` too, and thus we would break some more general Vim-pattern by this change. But it just requires a one-time adjustment for a permanent gain, which is much less of a problem.

> In the same vein, is there a reason there are two separate <plug> maps for ;? Seems "cohesive" to me to have one map for both of them, and easily done: keep track of which was used last and repeat that motion.

We cannot assume that one always wants to repeat the last motion type. What if I use `s`, then do some `df` operation, and then I would like to repeat `s`. So it's better to provide the special ones too. In my opinion, "cold-repeating" `f`/`t` has very limited use anyway. Also, universal `;`/`,` functionality is simple to achieve in a couple of lines with expression mappings, one just needs to update some global "last motion" state on the appropriate `Enter` events.

That said, the whole repeat functionality is in flux now, I'm working on a more uniform system, so I'd suggest let's return to this a bit later (if you want).
