### ISSUE TITLE
zf (create manual fold command) is broken

### ISSUE THREAD

**Issue by metalelf0** [ggandor/lightspeed.nvim#9]
Hey, just noticed this issue: when using your plugin I can't create manual folds anymore. `zf` triggers f-navigation. Disabling the plugin makes it work again.

**Comment by ggandor** [comment]
I cannot reproduce this. Let's see what could be the problem on your side... 1. Are you using the plugin with the default settings? 2. Do you use `zf` literally, or maybe you have an alias/shortcut defined for that with `nmap` (recursive)? 3. Do `zF` and `zt` work as expected?

**Comment by metalelf0** [comment]
1. I'm using the plugin with the default settings. 
2. `:map zf` returns:

```
o  z             <Plug>Lightspeed_s                                                                                                                                                                                                                                
x  z             <Plug>Lightspeed_s 
```

3. `zF` and `zT` don't work either.

**Comment by ggandor** [comment]
Then map `f/F/t/T` to anything else, and let's try whether that breaks `zf` too...

**Comment by metalelf0** [comment]
`:unmap f` alone is not enough. Also had to `:unmap z` to get `zf` back working.

**Comment by ggandor** [comment]
So if you `unmap z` only, then both the plugin and `zf` work again?

**Comment by ggandor** [comment]
Oh, okay, you're using it in Visual mode... Well, yeah, the plugin maps `z/Z` (because `s/S` are more adequate for surround plugins in that case). My bad, I forgot that `z` is used in `zf` and the like, I just wanted to make the mappings more consistent compared to Sneak. So, for the moment, `xmap` something else to `<Plug>Lightspeed_s/S` (before the plugin is loaded) - and I will reconsider the default mappings...
